### PR TITLE
fix to catch last entites

### PR DESCRIPTION
**Pull request by pimmeerdink**
Small change to catch entities that go up until last character when there is no tag (i.e. it is an '' (empty string) which will evaluate to False)

### CODE REVIEW

**Comment by pimmeerdink** [comment]
@ivyleavedtoadflax

**Comment by ivyleavedtoadflax** [comment]
Thanks for this @pimmeerdink, I will look into this.

**Comment by ivyleavedtoadflax** [comment]
Hmm i'm not sure why the CI has failed to run on this after all this time. Will try to kick start it now.

**Comment by ivyleavedtoadflax** [comment]
I just want to write a test for this, then i will merge - thanks again @pimmeerdink

**Pull request merged**
